swagger: '2.0'
info:
  version: v1
  title: REST API Documentation
  description: API Sample
  termsOfService: None
basePath: '/'
paths:
  /Vehicles:
    get:
      tags:
        - Vehicle
      operationId: VehiclesGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Vehicle'
      deprecated: false
definitions:
  Vehicle:
    type: object
    properties:
      vehicle_id:
        format: int32
        type: integer
        x-type-options:
          min: 1
          max: 1000
      description:
        type: string
        x-chance-type: sentence
      display_name:
        type: string
        x-chance-type: name
securityDefinitions: {}
